export const headCells = [
  {
    id: "HIER1",
    numeric: true,
    disablePadding: false,
    label: "HIER1",
    width: "100%",
  },
  {
    id: "LOCATION",
    numeric: true,
    disablePadding: false,
    label: "LOCATION",
    width: "100%",
  },
  {
    id: "TRN_NAME",
    numeric: true,
    disablePadding: false,
    label: "TRN TYPE",
    width: "130px",
  },
  {
    id: "TRN_POST_DATE",
    numeric: true,
    disablePadding: false,
    label: "END OF PERIOD",
    width: "150px",
  },
  {
    id: "QTY",
    numeric: true,
    disablePadding: false,
    label: "QTY",
    width: "100%",
  },
  {
    id: "COST",
    numeric: false,
    disablePadding: false,
    label: "COST",
    width: "100%",
  },
  {
    id: "RETAIL",
    numeric: true,
    disablePadding: false,
    label: "RETAIL",
    width: "100%",
  },
  {
    id: "ROLLED_QTY",
    numeric: false,
    disablePadding: true,
    label: "ROLLED QTY",
    width: "100%",
  },
  {
    id: "ROLLED_COST",
    numeric: false,
    disablePadding: true,
    label: "ROLLED COST",
    width: "100%",
  },
  {
    id: "ROLLED_RETAIL",
    numeric: false,
    disablePadding: true,
    label: "ROLLED RETAIL",
    width: "100%",
  },
  {
    id: "QTY_MATCHED",
    numeric: false,
    disablePadding: true,
    label: "QTY MATCHED",
    width: "100%",
  },
  {
    id: "COST_MATCHED",
    numeric: false,
    disablePadding: true,
    label: "COST MATCHED",
    width: "100%",
  },
  {
    id: "RETAIL_MATCHED",
    numeric: false,
    disablePadding: true,
    label: "RETAIL MATCHED",
    width: "100%",
  },
];
