export const headCells = [
  {
    id: "ITEM",
    numeric: true,
    disablePadding: false,
    label: "ITEM",
    width: "100px",
  },
  {
    id: "ERR_MSG",
    numeric: false,
    disablePadding: false,
    label: "ERR MSG",
    width: "120px",
  },
  {
    id: "ITEM_DESC",
    numeric: false,
    disablePadding: false,
    label: "ITEM DESC",
    width: "150px",
  },
  {
    id: "HIER1",
    numeric: false,
    disablePadding: true,
    label: "HIER1",
    width: "100%",
  },
  {
    id: "HIER1_DESC",
    numeric: false,
    disablePadding: true,
    label: "HIER1 DESC",
    width: "150px",
  },
  {
    id: "HIER2",
    numeric: false,
    disablePadding: true,
    label: "HIER2",
    width: "100%",
  },
  {
    id: "HIER2_DESC",
    numeric: false,
    disablePadding: true,
    label: "HIER2 DESC",
    width: "150px",
  },
  {
    id: "HIER3",
    numeric: false,
    disablePadding: true,
    label: "HIER3",
    width: "100%",
  },
  {
    id: "HIER3_DESC",
    numeric: false,
    disablePadding: true,
    label: "HIER3 DESC",
    width: "150px",
  },
  {
    id: "LOCATION_TYPE",
    numeric: true,
    disablePadding: false,
    label: "LOC TYPE",
    width: "90px",
  },
  {
    id: "LOCATION",
    numeric: true,
    disablePadding: false,
    label: "LOC",
    width: "100%",
  },
  {
    id: "LOCATION_NAME",
    numeric: true,
    disablePadding: false,
    label: "LOC NAME",
    width: "100px",
  },
  {
    id: "TRN_DATE",
    numeric: false,
    disablePadding: false,
    label: "TRN DATE",
    width: "100px",
  },
  {
    id: "TRN_NAME",
    numeric: true,
    disablePadding: false,
    label: "TRN TYPE",
    width: "100px",
  },
  {
    id: "QTY",
    numeric: false,
    disablePadding: true,
    label: "QTY",
    width: "100%",
  },
  {
    id: "UNIT_COST",
    numeric: true,
    disablePadding: false,
    label: "UNIT COST",
    width: "100px",
  },
  {
    id: "UNIT_RETAIL",
    numeric: true,
    disablePadding: false,
    label: "UNIT RETAIL",
    width: "120px",
  },
  {
    id: "TOTAL_COST",
    numeric: true,
    disablePadding: false,
    label: "TOTAL COST",
    width: "120px",
  },
  {
    id: "TOTAL_RETAIL",
    numeric: true,
    disablePadding: false,
    label: "TOTAL RETAIL",
    width: "120px",
  },
  {
    id: "REF_NO1",
    numeric: false,
    disablePadding: true,
    label: "REF NO1",
    width: "90px",
  },
  {
    id: "REF_NO2",
    numeric: true,
    disablePadding: false,
    label: "REF NO2",
    width: "90px",
  },
  {
    id: "REF_NO3",
    numeric: true,
    disablePadding: false,
    label: "REF NO3",
    width: "90px",
  },
  {
    id: "REF_NO4",
    numeric: true,
    disablePadding: false,
    label: "REF NO4",
    width: "90px",
  },
  {
    id: "CURRENCY",
    numeric: true,
    disablePadding: false,
    label: "CURRENCY",
    width: "90px",
  },
  {
    id: "CREATE_ID",
    numeric: true,
    disablePadding: false,
    label: "USER",
    width: "90px",
  },
  {
    id: "ERR_SEQ_NO",
    numeric: false,
    disablePadding: false,
    label: "ERR SEQ NO",
    width: "120px",
  },
  {
    id: "TRAN_SEQ_NO",
    numeric: false,
    disablePadding: true,
    label: "TRAN SEQ NO",
    width: "120px",
  },
];
