FROM node:alpine

WORKDIR /Allocation_react
COPY package.json ./
Run npm install -g npm@8.15.0
Run set NODE_OPTIONS=--max_old_space_size=4096
COPY . ./
COPY node_modules ./
EXPOSE 3000
CMD ["npm","start"]



# Use Node.js as the base image
FROM node:18.15.0-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the container
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --frozen-lockfile

# Install dependencies
RUN npm install

# Copy the app's source code to the container
COPY . .

# Build the React app
RUN npm build

# Serve the build
CMD ["npm", "serve", "-s", "build"]
