export const headCells = [
  {
    id: "LOC",
    numeric: true,
    disablePadding: false,
    label: "WH",
    width: "100px",
  },
  {
    id: "ITEM",
    numeric: false,
    disablePadding: false,
    label: "Sku",
    width: "250px",
  },
  {
    id: "ITEM_DESC",
    numeric: false,
    disablePadding: false,
    label: "Description",
    width: "100%",
  },
  {
    id: "DIFF_ID",
    numeric: false,
    disablePadding: true,
    label: "Variant",
    width: "100%",
  },
  {
    id: "VPN",
    numeric: false,
    disablePadding: true,
    label: "VPN",
    width: "100%",
  },
  {
    id: "HIER1",
    numeric: false,
    disablePadding: true,
    label: "Hier1",
    width: "100%",
  },
  {
    id: "HIER2",
    numeric: false,
    disablePadding: true,
    label: "Hier2",
    width: "100%",
  },
  {
    id: "HIER3",
    numeric: false,
    disablePadding: true,
    label: "Hier3",
    width: "100%",
  },
  {
    id: "HOLDBACK_QTY",
    numeric: false,
    disablePadding: true,
    label: "Holdback Qty",
    width: "100%",
  },
  {
    id: "HOLDBACK_TYPE",
    numeric: false,
    disablePadding: true,
    label: "Holdback Type",
    width: "100%",
  },
  {
    id: "AVAIL_QTY",
    numeric: false,
    disablePadding: true,
    label: "Avail Qty",
    width: "100%",
  },
  {
    id: "INACTIVE_QTY",
    numeric: true,
    disablePadding: false,
    label: "Inactive Qty",
    width: "100%",
  },
  {
    id: "PACK_IND",
    numeric: false,
    disablePadding: true,
    label: "Pck Ind",
    width: "100%",
  },
  {
    id: "REF_2",
    numeric: true,
    disablePadding: false,
    label: "Criteria Key",
    width: "100%",
  },
  {
    id: "ALLOC_CRITERIA",
    numeric: true,
    disablePadding: false,
    label: "Alloc Criteria",
    width: "100%",
  },
  {
    id: "PO_TYPE",
    numeric: false,
    disablePadding: false,
    label: "PO Type",
    width: "100%",
  },
  {
    id: "SIZE_PRF_IND",
    numeric: false,
    disablePadding: true,
    label: "Siz Prf",
    width: "100%",
  },
  {
    id: "SUBSTITUTE_IND",
    numeric: false,
    disablePadding: true,
    label: "Subs Ind",
    width: "100%",
  },
  // {
  //   id: "INVENT_IND",
  //   numeric: false,
  //   disablePadding: true,
  //   label: "Inv Ind",
  //   width: "100%",
  // },
  {
    id: "INNER_SIZE",
    numeric: true,
    disablePadding: false,
    label: "Inner",
    width: "100%",
  },
  {
    id: "CASE_SIZE",
    numeric: false,
    disablePadding: true,
    label: "Case",
    width: "100%",
  },
  {
    id: "SOM_TYPE",
    numeric: true,
    disablePadding: false,
    label: "Store Packs",
    width: "100%",
  },
  {
    id: "SEASON",
    numeric: true,
    disablePadding: false,
    label: "Season",
    width: "100%",
  },
  {
    id: "SPLIT_IND",
    numeric: true,
    disablePadding: false,
    label: "Split",
    width: "100%",
  },
  // {    id: "ERR_IND",
  //   numeric: true,
  //   disablePadding: false,
  //   label: "Error Type",
  //   width: "100%",
  // },
  {
    id: "ERR_MESSAGE",
    numeric: false,
    disablePadding: true,
    label: "Error Message",
    width: "100%",
  },
];