export const GET_STAGEPROCEESING_REQUEST = "GET_STAGEPROCEESING_REQUEST";
export const GET_STAGEPROCEESING_SUCCESS = "GET_STAGEPROCEESING_SUCCESS";
export const GET_STAGEPROCEESING_ERROR = "GET_STAGEPROCEESING_ERROR";
export const RESET_STAGEPROCESSING = "RESET_STAGEPROCESSING";
export const GET_ERRORPROCESSING_REQUEST = "GET_ERRORPROCESSING_REQUEST";
export const GET_ERRORPROCESSING_SUCCESS = "GET_ERRORPROCESSING_SUCCESS";
export const GET_ERRORPROCESSING_ERROR = "GET_ERRORPROCESSING_ERROR";
export const POST_ERRORPROCESSING_REQUEST = "POST_ERRORPROCESSING_REQUEST";
export const POST_ERRORPROCESSING_SUCCESS = "POST_ERRORPROCESSING_SUCCESS";
export const POST_ERRORPROCESSING_ERROR = "POST_ERRORPROCESSING_ERROR";
export const GET_HIER2DATA_REQUEST = "GET_HIER2DATA_REQUEST";
export const GET_HIER2DATA_SUCCESS = "GET_HIER2DATA_SUCCESS";
export const GET_HIER2DATA_ERROR = "GET_HIER2DATA_ERROR";
export const GET_LOCATIONDATA_REQUEST = "GET_LOCATIONDATA_REQUEST";
export const GET_LOCATIONDATA_SUCCESS = "GET_LOCATIONDATA_SUCCESS";
export const GET_LOCATIONDATA_ERROR = "GET_LOCATIONDATA_ERROR";
export const GET_SYSTEMCONFIG_REQUEST = "GET_SYSTEMCONFIG_REQUEST";
export const GET_SYSTEMCONFIG_SUCCESS = "GET_SYSTEMCONFIG_SUCCESS";
export const GET_SYSTEMCONFIG_ERROR = "GET_SYSTEMCONFIG_ERROR";
export const POST_SYSTEMCONFIG_REQUEST = "POST_SYSTEMCONFIG_REQUEST";
export const POST_SYSTEMCONFIG_SUCCESS = "POST_SYSTEMCONFIG_SUCCESS";
export const POST_SYSTEMCONFIG_ERROR = "POST_SYSTEMCONFIG_ERROR";
export const RESET_SYSTEMCONFIG = "RESET_SYSTEMCONFIG";
export const GET_DAILYCOUNT_REQUEST = "GET_DAILYCOUNT_REQUEST";
export const GET_DAILYCOUNT_SUCCESS = "GET_DAILYCOUNT_SUCCESS";
export const GET_DAILYCOUNT_ERROR = "GET_DAILYCOUNT_ERROR";
export const GET_STAGECOUNT_REQUEST = "GET_STAGECOUNT_REQUEST";
export const GET_STAGECOUNT_SUCCESS = "GET_STAGECOUNT_SUCCESS";
export const GET_STAGECOUNT_ERROR = "GET_STAGECOUNT_ERROR";
export const GET_ERRORCOUNT_REQUEST = "GET_ERRORCOUNT_REQUEST";
export const GET_ERRORCOUNT_SUCCESS = "GET_ERRORCOUNT_SUCCESS";
export const GET_ERRORCOUNT_ERROR = "GET_ERRORCOUNT_ERROR";
export const GET_DAILY_SKU_ROLLUPDATA_REQUEST = "GET_DAILY_SKU_ROLLUPDATA_REQUEST";
export const GET_DAILY_SKU_ROLLUPDATA_SUCCESS = "GET_HIER2DATA_SUCCESS";
export const GET_DAILY_SKU_ROLLUPDATA_ERROR = "GET_DAILY_SKU_ROLLUPDATA_ERROR";
export const GET_HIER1RECDATA_REQUEST = "GET_HIER1RECDATA_REQUEST";
export const GET_HIER1RECDATA_SUCCESS = "GET_HIER1RECDATA_SUCCESS";
export const GET_HIER1RECDATA_ERROR = "GET_HIER1RECDATA_ERROR";
export const GET_LOCATIONRECDATA_REQUEST = "GET_LOCATIONRECDATA_REQUEST";
export const GET_LOCATIONRECDATA_SUCCESS = "GET_LOCATIONRECDATA_SUCCESS";
export const GET_LOCATIONRECDATA_ERROR = "GET_LOCATIONRECDATA_ERROR";
export const GET_INQUIRYDATA_REQUEST = "GET_INQUIRYDATA_REQUEST";
export const GET_INQUIRYDATA_SUCCESS = "GET_INQUIRYDATA_SUCCESS";
export const GET_INQUIRYDATA_ERROR = "GET_INQUIRYDATA_ERROR";
export const RESET_INQUIRY = "RESET_INQUIRY";
export const GET_TRANSACTIONREVERSAL_REQUEST = "GET_TRANSACTIONREVERSAL_REQUEST";
export const GET_TRANSACTIONREVERSAL_SUCCESS = "GET_TRANSACTIONREVERSAL_SUCCESS";
export const GET_TRANSACTIONREVERSAL_ERROR = "GET_TRANSACTIONREVERSAL_ERROR";
export const POST_TRANSACTIONREVERSAL_REQUEST = "POST_TRANSACTIONREVERSAL_REQUEST";
export const POST_TRANSACTIONREVERSAL_SUCCESS = "POST_TRANSACTIONREVERSAL_SUCCESS";
export const POST_TRANSACTIONREVERSAL_ERROR = "POST_TRANSACTIONREVERSAL_ERROR";
export const POST_TRANSACTIONCANCEL_REQUEST = "POST_TRANSACTIONCANCEL_REQUEST";
export const POST_TRANSACTIONCANCEL_SUCCESS = "POST_TRANSACTIONCANCEL_SUCCESS";
export const POST_TRANSACTIONCANCEL_ERROR = "POST_TRANSACTIONCANCEL_ERROR";
export const RESET_TRANSACTIONREVERSAL = "RESET_TRANSACTIONREVERSAL";

export const GET_COSTCHANGE_REQUEST = "GET_COSTCHANGE_REQUEST";
export const GET_COSTCHANGE_SUCCESS = "GET_COSTCHANGE_SUCCESS";
export const GET_COSTCHANGE_ERROR = "GET_COSTCHANGE_ERROR";
export const POST_COSTCHANGE_REQUEST = "POST_COSTCHANGE_REQUEST";
export const POST_COSTCHANGE_SUCCESS = "POST_COSTCHANGE_SUCCESS";
export const POST_COSTCHANGE_ERROR = "POST_COSTCHANGE_ERROR";


export const GET_GLACCOUNT_REQUEST = "GET_GLACCOUNT_REQUEST";
export const GET_GLACCOUNT_SUCCESS = "GET_GLACCOUNT_SUCCESS";
export const GET_GLACCOUNT_ERROR = "GET_GLACCOUNT_ERROR";
export const POST_GLACCOUNT_REQUEST = "POST_GLACCOUNT_REQUEST";
export const POST_GLACCOUNT_SUCCESS = "POST_GLACCOUNT_SUCCESS";
export const POST_GLACCOUNT_ERROR = "POST_GLACCOUNT_ERROR";
export const GET_GLACCOUNTCREATION_REQUEST = "GET_GLACCOUNTCREATION_REQUEST";
export const GET_GLACCOUNTCREATION_SUCCESS = "GET_GLACCOUNTCREATION_SUCCESS";
export const GET_GLACCOUNTCREATION_ERROR = "GET_GLACCOUNT_ERROR";
export const POST_GLACCOUNTCREATION_REQUEST = "POST_GLACCOUNTCREATION_REQUEST";
export const POST_GLACCOUNTCREATION_SUCCESS = "POST_GLACCOUNTCREATION_SUCCESS";
export const POST_GLACCOUNTCREATION_ERROR = "POST_GLACCOUNTCREATION_ERROR";
export const GET_GLCURRENCY_REQUEST = "GET_GLCURRENCY_REQUEST";
export const GET_GLCURRENCY_SUCCESS = "GET_GLCURRENCY_SUCCESS";
export const GET_GLCURRENCY_ERROR = "GET_GLCURRENCY_ERROR";
export const POST_GLCREATION_REQUEST = "POST_GLCREATION_REQUEST";
export const POST_GLCREATION_SUCCESS = "POST_GLCREATION_SUCCESS";
export const POST_GLCREATION_ERROR = "POST_GLCREATION_ERROR";

export const GET_FINANCEINTERFACE_REQUEST = "GET_FINANCEINTERFACE_REQUEST";
export const GET_FINANCEINTERFACE_SUCCESS = "GET_FINANCEINTERFACE_SUCCESS";
export const GET_FINANCEINTERFACE_ERROR = "GET_FINANCEINTERFACE_ERROR";

export const GET_DAILYVIEW_REQUEST = "GET_DAILYVIEW_REQUEST";
export const GET_DAILYVIEW_SUCCESS = "GET_DAILYVIEW_SUCCESS";
export const GET_DAILYVIEW_ERROR = "GET_DAILYVIEW_ERROR";

export const GET_SUBLEDGERCOST_REQUEST = "GET_SUBLEDGERCOST_REQUEST";
export const GET_SUBLEDGERCOST_SUCCESS = "GET_SUBLEDGERCOST_SUCCESS";
export const GET_SUBLEDGERCOST_ERROR = "GET_SUBLEDGERCOST_ERROR";

export const POST_SYSCONFIGCREATION_REQUEST = "POST_SYSCONFIGCREATION_REQUEST";
export const POST_SYSCONFIGCREATION_SUCCESS = "POST_SYSCONFIGCREATION_SUCCESS";
export const POST_SYSCONFIGCREATION_ERROR = "POST_SYSCONFIGCREATION_ERROR";
export const GET_GLPRIMARY_REQUEST = "GET_GLPRIMARY_REQUEST";
export const GET_GLPRIMARY_SUCCESS = "GET_GLPRIMARY_SUCCESS";
export const GET_GLPRIMARY_ERROR = "GET_GLPRIMARY_ERROR";


export const GET_WAREHOUSE_REQUEST = "GET_WAREHOUSE_REQUEST";
export const GET_WAREHOUSE_SUCCESS = "GET_WAREHOUSE_SUCCESS";
export const GET_WAREHOUSE_ERROR = "GET_WAREHOUSE_ERROR";
export const GET_SUPPLIER_REQUEST = "GET_SUPPLIER_REQUEST";
export const GET_SUPPLIER_SUCCESS = "GET_SUPPLIER_SUCCESS";
export const GET_SUPPLIER_ERROR = "GET_SUPPLIER_ERROR";
export const GET_SUPPLIERSITE_REQUEST = "GET_SUPPLIERSITE_REQUEST";
export const GET_SUPPLIERSITE_SUCCESS = "GET_SUPPLIERSITE_SUCCESS";
export const GET_SUPPLIERSITE_ERROR = "GET_SUPPLIERSITE_ERROR";
export const GET_PACKNO_REQUEST = "GET_PACKNO_REQUEST";
export const GET_PACKNO_SUCCESS = "GET_PACKNO_SUCCESS";
export const GET_PACKNO_ERROR = "GET_PACKNO_ERROR";
export const GET_ITEMPARENT_REQUEST = "GET_ITEMPARENT_REQUEST";
export const GET_ITEMPARENT_SUCCESS = "GET_ITEMPARENT_SUCCESS";
export const GET_ITEMPARENT_ERROR = "GET_ITEMPARENT_ERROR";
export const GET_DIFF_REQUEST = "GET_DIFF_REQUEST";
export const GET_DIFF_SUCCESS = "GET_DIFF_SUCCESS";
export const GET_DIFF_ERROR = "GET_DIFF_ERROR";
export const GET_SKU_REQUEST = "GET_SKU_REQUEST";
export const GET_SKU_SUCCESS = "GET_SKU_SUCCESS";
export const GET_SKU_ERROR = "GET_SKU_ERROR";
export const GET_ITEM_LIST_HEAD_REQUEST = "GET_ITEM_LIST_HEAD_REQUEST";
export const GET_ITEM_LIST_HEAD_SUCCESS = "GET_ITEM_LIST_HEAD_SUCCESS";
export const GET_ITEM_LIST_HEAD_ERROR = "GET_ITEM_LIST_HEAD_ERROR";
export const GET_VPN_REQUEST = "GET_VPN_REQUEST";
export const GET_VPN_SUCCESS = "GET_VPN_SUCCESS";
export const GET_VPN_ERROR = "GET_VPN_ERROR";
export const GET_UDA_REQUEST = "GET_UDA_REQUEST";
export const GET_UDA_SUCCESS = "GET_UDA_SUCCESS";
export const GET_EXCLUDEUDA_ERROR = "GET_EXCLUDEUDA_ERROR";
export const GET_EXCLUDEUDA_REQUEST = "GET_EXCLUDEUDA_REQUEST";
export const GET_EXCLUDEUDA_SUCCESS = "GET_EXCLUDEUDA_SUCCESS";
export const GET_UDA_ERROR = "GET_UDA_ERROR";
export const GET_PO_REQUEST = "GET_PO_REQUEST";
export const GET_PO_SUCCESS = "GET_PO_SUCCESS";
export const GET_PO_ERROR = "GET_PO_ERROR";
export const GET_PO_TYPE_REQUEST = "GET_PO_TYPE_REQUEST";
export const GET_PO_TYPE_SUCCESS = "GET_PO_TYPE_SUCCESS";
export const GET_PO_TYPE_ERROR = "GET_PO_TYPE_ERROR";
export const GET_HIER_REQUEST = "GET_HIER_REQUEST";
export const GET_HIER_SUCCESS = "GET_HIER_SUCCESS";
export const GET_HIER_ERROR = "GET_HIER_ERROR";
export const GET_HIER2_REQUEST = "GET_HIER2_REQUEST";
export const GET_HIER2_SUCCESS = "GET_HIER2_SUCCESS";
export const GET_HIER2_ERROR = "GET_HIER2_ERROR";
export const GET_HIER3_REQUEST = "GET_HIER3_REQUEST";
export const GET_HIER3_SUCCESS = "GET_HIER3_SUCCESS";
export const GET_HIER3_ERROR = "GET_HIER3_ERROR";
export const GET_ASN_REQUEST = "GET_ASN_REQUEST";
export const GET_ASN_SUCCESS = "GET_ASN_SUCCESS";
export const GET_ASN_ERROR = "GET_ASN_ERROR";
export const GET_TSF_REQUEST = "GET_TSF_REQUEST";
export const GET_TSF_SUCCESS = "GET_TSF_SUCCESS";
export const GET_TSF_ERROR = "GET_TSF_ERROR";

export const GET_ALLOC_LEVEL_REQUEST = "GET_ALLOC_LEVEL_REQUEST";
export const GET_ALLOC_LEVEL_SUCCESS = "GET_ALLOC_LEVEL_SUCCESS";
export const GET_ALLOC_LEVEL_ERROR = "GET_ALLOC_LEVEL_ERROR";
export const GET_ALLOC_TYPE_REQUEST = "GET_ALLOC_TYPE_REQUEST";
export const GET_ALLOC_TYPE_SUCCESS = "GET_ALLOC_TYPE_SUCCESS";
export const GET_ALLOC_TYPE_ERROR = "GET_ALLOC_TYPE_ERROR";
export const GET_CONTEXT_TYPE_REQUEST = "GET_CONTEXT_TYPE_REQUEST";
export const GET_CONTEXT_TYPE_SUCCESS = "GET_CONTEXT_TYPE_SUCCESS";
export const GET_CONTEXT_TYPE_ERROR = "GET_CONTEXT_TYPE_ERROR";
export const GET_STATUS_REQUEST = "GET_STATUS_REQUEST";
export const GET_STATUS_SUCCESS = "GET_STATUS_SUCCESS";
export const GET_STATUS_ERROR = "GET_STATUS_ERROR";
export const GET_PROMOTION_REQUEST = "GET_PROMOTION_REQUEST";
export const GET_PROMOTION_SUCCESS = "GET_PROMOTION_SUCCESS";
export const GET_PROMOTION_ERROR = "GET_PROMOTION_ERROR";
export const GET_ALLOC_CRITERIA_REQUEST = "GET_ALLOC_CRITERIA_REQUEST";
export const GET_ALLOC_CRITERIA_SUCCESS = "GET_ALLOC_CRITERIA_SUCCESS";
export const GET_ALLOC_CRITERIA_ERROR = "GET_ALLOC_CRITERIA_ERROR";
export const GET_ALLOCNO_REQUEST = "GET_ALLOCNO_REQUEST";
export const GET_ALLOCNO_SUCCESS = "GET_ALLOCNO_SUCCESS";
export const GET_ALLOCNO_ERROR = "GET_ALLOCNO_ERROR";

export const POST_ALLOCRESULT_REQUEST = "POST_ALLOCRESULT_REQUEST";
export const POST_ALLOCRESULT_SUCCESS = "POST_ALLOCRESULT_SUCCESS";
export const POST_ALLOCRESULT_ERROR = "POST_ALLOCRESULT_ERROR";
export const POST_ALLOCINSERT_REQUEST = "POST_ALLOCINSERT_REQUEST";
export const POST_ALLOCINSERT_SUCCESS = "POST_ALLOCINSERT_SUCCESS";
export const POST_ALLOCINSERT_ERROR = "POST_ALLOCINSERT_ERROR";
export const POST_ALLOCRESULTCWH_REQUEST = "POST_ALLOCRESULTCWH_REQUEST";
export const POST_ALLOCRESULTCWH_SUCCESS = "POST_ALLOCRESULTCWH_SUCCESS";
export const POST_ALLOCRESULTCWH_ERROR = "POST_ALLOCRESULTCWH_ERROR";
export const POST_ALLOCRESULTCASN_REQUEST = "POST_ALLOCRESULTCASN_REQUEST";
export const POST_ALLOCRESULTCASN_SUCCESS = "POST_ALLOCRESULTCASN_SUCCESS";
export const POST_ALLOCRESULTCASN_ERROR = "POST_ALLOCRESULTCASN_ERROR";
export const POST_ALLOCRESULTCTSF_REQUEST = "POST_ALLOCRESULTCTSF_REQUEST";
export const POST_ALLOCRESULTCTSF_SUCCESS = "POST_ALLOCRESULTCTSF_SUCCESS";
export const POST_ALLOCRESULTCTSF_ERROR = "POST_ALLOCRESULTCTSF_ERROR";

export const GET_ALLOCHEADDETAILS_REQUEST = "GET_ALLOCHEADDETAILS_REQUEST";
export const GET_ALLOCHEADDETAILS_SUCCESS = "GET_ALLOCHEADDETAILS_SUCCESS";
export const GET_ALLOCHEADDETAILS_ERROR = "GET_ALLOCHEADDETAILS_ERROR";
export const GET_QTYLIMITS_REQUEST = "GET_QTYLIMITS_REQUEST";
export const GET_QTYLIMITS_SUCCESS = "GET_QTYLIMITS_SUCCESS";
export const GET_QTYLIMITS_ERROR = "GET_QTYLIMITS_ERROR";
export const GET_ALLOCNODETAILS_REQUEST = "GET_ALLOCNODETAILS_REQUEST";
export const GET_ALLOCNODETAILS_SUCCESS = "GET_ALLOCNODETAILS_SUCCESS";
export const GET_ALLOCNODETAILS_ERROR = "GET_ALLOCNODETAILS_ERROR";
export const GET_UPDATEQTYLIMITS_REQUEST = "GET_UPDATEQTYLIMITS_REQUEST";
export const GET_UPDATEQTYLIMITS_SUCCESS = "GET_UPDATEQTYLIMITS_SUCCESS";
export const GET_UPDATEQTYLIMITS_ERROR = "GET_UPDATEQTYLIMITS_ERROR";
export const GET_OKQTYLIMITSSRN_REQUEST = "GET_OKQTYLIMITSSRN_REQUEST";
export const GET_OKQTYLIMITSSRN_SUCCESS = "GET_OKQTYLIMITSSRN_SUCCESS";
export const GET_OKQTYLIMITSSRN_ERROR = "GET_OKQTYLIMITSSRN_ERROR";

export const GET_UPDATESELINDCREATE_REQUEST = "GET_UPDATESELINDCREATE_REQUEST";
export const GET_UPDATESELINDCREATE_SUCCESS = "GET_UPDATESELINDCREATE_SUCCESS";
export const GET_UPDATESELINDCREATE_ERROR = "GET_UPDATESELINDCREATE_ERROR";


export const GET_ALLOC_ITEMS_REQUEST = "GET_ALLOC_ITEMS_REQUEST";
export const GET_ALLOC_ITEMS_SUCCESS = "GET_ALLOC_ITEMS_SUCCESS";
export const GET_ALLOC_ITEMS_ERROR = "GET_ALLOC_ITEMS_ERROR";
/* LIKE ITEM */
export const POST_LIKE_INSERT_REQUEST = "POST_LIKE_INSERT_REQUEST";
export const POST_LIKE_INSERT_SUCCESS = "POST_LIKE_INSERT_SUCCESS";
export const POST_LIKE_INSERT_ERROR = "POST_LIKE_INSERT_ERROR";

export const POST_DEL_MAPPED_REQUEST = "POST_DEL_MAPPED_REQUEST";
export const POST_DEL_MAPPED_SUCCESS = "POST_DEL_MAPPED_SUCCESS";
export const POST_DEL_MAPPED_ERROR = "POST_DEL_MAPPED_ERROR";

export const POST_MAP_ITEMS_REQUEST = "POST_MAP_ITEMS_REQUEST";
export const POST_MAP_ITEMS_SUCCESS = "POST_MAP_ITEMS_SUCCESS";
export const POST_MAP_ITEMS_ERROR = "POST_MAP_ITEMS_ERROR";

export const POST_NOOFSKUS_REQUEST = "POST_NOOFSKUS_REQUEST";
export const POST_NOOFSKUS_SUCCESS = "POST_NOOFSKUS_SUCCESS";
export const POST_NOOFSKUS_ERROR = "POST_NOOFSKUS_ERROR";

export const GET_ALLOC_AVAIL_QTY_REQUEST = "GET_ALLOC_AVAIL_QTY_REQUEST";
export const GET_ALLOC_AVAIL_QTY_SUCCESS = "GET_ALLOC_AVAIL_QTY_SUCCESS";
export const GET_ALLOC_AVAIL_QTY_ERROR = "GET_ALLOC_AVAIL_QTY_ERROR";
export const GET_ALLOC_AVAIL_SEARCH_REQUEST = "GET_ALLOC_AVAIL_SEARCH_REQUEST";
export const GET_ALLOC_AVAIL_SEARCH_SUCCESS = "GET_ALLOC_AVAIL_SEARCH_SUCCESS";
export const GET_ALLOC_AVAIL_SEARCH_ERROR = "GET_ALLOC_AVAIL_SEARCH_ERROR";

//RULES AND LOCATIOM//
export const GET_RULESTYPE_REQUEST = "GET_RULESTYPE_REQUEST";
export const GET_RULESTYPE_SUCCESS = "GET_RULESTYPE_SUCCESS";
export const GET_RULESTYPE_ERROR = "GET_RULESTYPE_ERROR";
export const GET_NEEDTYPE_REQUEST = "GET_NEEDTYPE_REQUEST";
export const GET_NEEDTYPE_SUCCESS = "GET_NEEDTYPE_SUCCESS";
export const GET_NEEDTYPE_ERROR = "GET_NEEDTYPE_ERROR";
export const GET_ALLOCATETOTYPE_REQUEST = "GET_ALLOCATETOTYPE_REQUEST";
export const GET_ALLOCATETOTYPE_SUCCESS = "GET_ALLOCATETOTYPE_SUCCESS";
export const GET_ALLOCATETOTYPE_ERROR = "GET_ALLOCATETOTYPE_ERROR";
export const GET_HIERARCHYTYPE_REQUEST = "GET_HIERARCHYTYPE_REQUEST";
export const GET_HIERARCHYTYPE_SUCCESS = "GET_HIERARCHYTYPE_SUCCESS";
export const GET_HIERARCHYTYPE_ERROR = "GET_HIERARCHYTYPE_ERROR";
export const GET_FETCHLOCATIONDATA_REQUEST = "GET_FETCHLOCATIONDATA_REQUEST";
export const GET_FETCHLOCATIONDATA_SUCCESS = "GET_FETCHLOCATIONDATA_SUCCESS";
export const GET_FETCHLOCATIONDATA_ERROR = "GET_FETCHLOCATIONDATA_ERROR";
export const GET_LOCATIONRL_REQUEST = "GET_LOCATIONRL_REQUEST";
export const GET_LOCATIONRL_SUCCESS = "GET_LOCATIONRL_SUCCESS";
export const GET_LOCATIONRL_ERROR = "GET_LOCATIONRL_ERROR";
export const GET_LOCATIONLISTRL_REQUEST = "GET_LOCATIONLISTRL_REQUEST";
export const GET_LOCATIONLISTRL_SUCCESS = "GET_LOCATIONLISTRL_SUCCESS";
export const GET_LOCATIONLISTRL_ERROR = "GET_LOCATIONLISTRL_ERROR";
export const GET_LOCATIONTRAITSRL_REQUEST = "GET_LOCATIONTRAITSRL_REQUEST";
export const GET_LOCATIONTRAITSRL_SUCCESS = "GET_LOCATIONTRAITSRL_SUCCESS";
export const GET_LOCATIONTRAITSRL_ERROR = "GET_LOCATIONTRAITSRL_ERROR";
export const GET_CLEARANCERL_REQUEST = "GET_CLEARANCERL_REQUEST";
export const GET_CLEARANCERL_SUCCESS = "GET_CLEARANCERL_SUCCESS";
export const GET_CLEARANCERL_ERROR = "GET_CLEARANCERL_ERROR";
export const GET_STATUSRL_REQUEST = "GET_STATUSRL_REQUEST";
export const GET_STATUSRL_SUCCESS = "GET_STATUSRL_SUCCESS";
export const GET_STATUSRL_ERROR = "GET_STATUSRL_ERROR";
export const GET_UPDATERULESRLRL_REQUEST = "GET_UPDATERULESRLRL_REQUEST";
export const GET_UPDATERULESRLRL_SUCCESS = "GET_UPDATERULESRLRL_SUCCESS";
export const GET_UPDATERULESRLRL_ERROR = "GET_UPDATERULESRLRL_ERROR";
export const GET_FETCHLOCGRID_REQUEST = "GET_FETCHLOCGRID_REQUEST";
export const GET_FETCHLOCGRID_SUCCESS = "GET_FETCHLOCGRID_SUCCESS";
export const GET_FETCHLOCGRID_ERROR = "GET_FETCHLOCGRID_ERROR";

export const GET_UPDATELOCATIONRL_REQUEST = "GET_UPDATELOCATIONRL_REQUEST";
export const GET_UPDATELOCATIONRL_SUCCESS = "GET_UPDATELOCATIONRL_SUCCESS";
export const GET_UPDATELOCATIONRL_ERROR = "GET_UPDATELOCATIONRL_ERROR";
export const GET_DELETELOCATIONRL_REQUEST = "GET_DELETELOCATIONRL_REQUEST";
export const GET_DELETELOCATIONRL_SUCCESS = "GET_DELETELOCATIONRL_SUCCESS";
export const GET_DELETELOCATIONRL_ERROR = "GET_DELETELOCATIONRL_ERROR";
export const GET_LOADWEIGHTCHANGERL_REQUEST = "GET_LOADWEIGHTCHANGERL_REQUEST";
export const GET_LOADWEIGHTCHANGERL_SUCCESS = "GET_LOADWEIGHTCHANGERL_SUCCESS";
export const GET_LOADWEIGHTCHANGERL_ERROR = "GET_LOADWEIGHTCHANGERL_ERROR";
export const GET_LOADRULEDATERL_REQUEST = "GET_LOADRULEDATERL_REQUEST";
export const GET_LOADRULEDATERL_SUCCESS = "GET_LOADRULEDATERL_SUCCESS";
export const GET_LOADRULEDATERL_ERROR = "GET_LOADRULEDATERL_ERROR";
export const GET_RETRIEVERULEDATERL_REQUEST = "GET_RETRIEVERULEDATERL_REQUEST";
export const GET_RETRIEVERULEDATERL_SUCCESS = "GET_RETRIEVERULEDATERL_SUCCESS";
export const GET_RETRIEVERULEDATERL_ERROR = "GET_RETRIEVERULEDATERL_ERROR";
export const GET_UPDATECHANGEWEIGHTSRL_REQUEST = "GET_UPDATECHANGEWEIGHTSRL_REQUEST";
export const GET_UPDATECHANGEWEIGHTSRL_SUCCESS = "GET_UPDATECHANGEWEIGHTSRL_SUCCESS";
export const GET_UPDATECHANGEWEIGHTSRL_ERROR = "GET_UPDATECHANGEWEIGHTSRL_ERROR";

export const GET_UPDATESIZEPROFILEINDRL_REQUEST = "GET_UPDATESIZEPROFILEINDRL_REQUEST";
export const GET_UPDATESIZEPROFILEINDRL_SUCCESS = "GET_UPDATESIZEPROFILEINDRL_SUCCESS";
export const GET_UPDATESIZEPROFILEINDRL_ERROR = "GET_UPDATESIZEPROFILEINDRL_ERROR";


export const GET_UPDATEWHINDRL_REQUEST = "GET_UPDATEWHINDRL_REQUEST";
export const GET_UPDATEWHINDRL_SUCCESS = "GET_UPDATEWHINDRL_SUCCESS";
export const GET_UPDATEWHINDRL_ERROR = "GET_UPDATEWHINDRL_ERROR";


export const GET_INSLOCRL_REQUEST = "GET_INSLOCRL_REQUEST";
export const GET_INSLOCRL_SUCCESS = "GET_INSLOCRL_SUCCESS";
export const GET_INSLOCRL_ERROR = "GET_INSLOCRL_ERROR";


export const GET_RTVRLDATA_REQUEST = "GET_RTVRLDATA_REQUEST";
export const GET_RTVRLDATA_SUCCESS = "GET_RTVRLDATA_SUCCESS";
export const GET_RTVRLDATA_ERROR = "GET_RTVRLDATA_ERROR";


//ALLOCATION SWITCH TABS FUNCTION

export const GET_SWITCHTABFUNC_REQUEST = "GET_SWITCHTABFUNC_REQUEST";
export const GET_SWITCHTABFUNC_SUCCESS = "GET_SWITCHTABFUNC_SUCCESS";
export const GET_SWITCHTABFUNC_ERROR = "GET_SWITCHTABFUNC_ERROR";

//ALLOCATION CREATE SCREEN BUTTONS
export const GET_DELETECREATEGRID_REQUEST = "GET_DELETECREATEGRID_REQUEST";
export const GET_DELETECREATEGRID_SUCCESS = "GET_DELETECREATEGRID_SUCCESS";
export const GET_DELETECREATEGRID_ERROR = "GET_DELETECREATEGRID_ERROR";
export const GET_CREATEREFRESHGRID_REQUEST = "GET_CREATEREFRESHGRID_REQUEST";
export const GET_CREATEREFRESHGRID_SUCCESS = "GET_CREATEREFRESHGRID_SUCCESS";
export const GET_CREATEREFRESHGRID_ERROR = "GET_CREATEREFRESHGRID_ERROR";
export const GET_SPLITCREATEFUNCTION_REQUEST = "GET_SPLITCREATEFUNCTION_REQUEST";
export const GET_SPLITCREATEFUNCTION_SUCCESS = "GET_SPLITCREATEFUNCTION_SUCCESS";
export const GET_SPLITCREATEFUNCTION_ERROR = "GET_SPLITCREATEFUNCTION_ERROR";

//CALCULATION
export const POST_CALC_REQUEST = "POST_CALC_REQUEST";
export const POST_CALC_SUCCESS = "POST_CALC_SUCCESS";
export const POST_CALC_ERROR = "POST_CALC_ERROR";
export const POST_CREATEGRIDDF_REQUEST = "POST_CREATEGRIDDF_REQUEST";
export const POST_CREATEGRIDDF_SUCCESS = "POST_CREATEGRIDDF_SUCCESS";
export const POST_CREATEGRIDDF_ERROR = "POST_CREATEGRIDDF_ERROR";


/*ALLOC DETAIL VALIDATION & RETRIEVE GRID DATA START*/
export const POST_ALLOCDTLTAB_REQUEST = "POST_ALLOCDTLTAB_REQUEST";
export const POST_ALLOCDTLTAB_SUCCESS = "POST_ALLOCDTLTAB_SUCCESS";
export const POST_ALLOCDTLTAB_ERROR = "POST_ALLOCDTLTAB_ERROR";

export const POST_ALLOCDTLRTV_REQUEST = "POST_ALLOCDTLRTV_REQUEST";
export const POST_ALLOCDTLRTV_SUCCESS = "POST_ALLOCDTLRTV_SUCCESS";
export const POST_ALLOCDTLRTV_ERROR = "POST_ALLOCDTLRTV_ERROR";

export const POST_SPREADALLOC_REQUEST = "POST_SPREADALLOC_REQUEST";
export const POST_SPREADALLOC_SUCCESS = "POST_SPREADALLOC_SUCCESS";
export const POST_SPREADALLOC_ERROR = "POST_SPREADALLOC_ERROR";

export const POST_SIZEPROF_REQUEST = "POST_SIZEPROF_REQUEST";
export const POST_SIZEPROF_SUCCESS = "POST_SIZEPROF_SUCCESS";
export const POST_SIZEPROF_ERROR = "POST_SIZEPROF_ERROR";
//SIZE DETAIL
export const POST_SIZEDETAILS_REQUEST = "POST_SIZEDETAILS_REQUEST";
export const POST_SIZEDETAILS_SUCCESS = "POST_SIZEDETAILS_SUCCESS";
export const POST_SIZEDETAILS_ERROR = "POST_SIZEDETAILS_ERROR";
export const POST_SIZEHEADERDETAILS_REQUEST = "POST_SIZEHEADERDETAILS_REQUEST";
export const POST_SIZEHEADERDETAILS_SUCCESS = "POST_SIZEHEADERDETAILS_SUCCESS";
export const POST_SIZEHEADERDETAILS_ERROR = "POST_SIZEHEADERDETAILS_ERROR";
export const POST_SIZEUPDATEDETAILS_REQUEST = "POST_SIZEUPDATEDETAILS_REQUEST";
export const POST_SIZEUPDATEDETAILS_SUCCESS = "POST_SIZEUPDATEDETAILS_SUCCESS";
export const POST_SIZEUPDATEDETAILS_ERROR = "POST_SIZEUPDATEDETAILS_ERROR";

export const POST_COPYAD_REQUEST = "POST_COPYAD_REQUEST";
export const POST_COPYAD_SUCCESS = "POST_COPYAD_SUCCESS";
export const POST_COPYAD_ERROR = "POST_COPYAD_ERROR";

export const POST_FETCHNN_REQUEST = "POST_FETCHNN_REQUEST";
export const POST_FETCHNN_SUCCESS = "POST_COPYAD_SUCCESS";
export const POST_FETCHNN_ERROR = "POST_COPYAD_ERROR";
/*ALLOC DETAIL VALIDATION & RETRIEVE GRID DATA END*/
export const POST_ALLOCQTY_REQUEST = "POST_ALLOCQTY_REQUEST";
export const POST_ALLOCQTY_SUCCESS = "POST_ALLOCQTY_SUCCESS";
export const POST_ALLOCQTY_ERROR = "POST_ALLOCQTY_ERROR";

/* WHATIF */
export const POST_RETRIEVEWHATIF_REQUEST = "POST_RETRIEVEWHATIF_REQUEST";
export const POST_RETRIEVEWHATIF_SUCCESS = "POST_RETRIEVEWHATIF_SUCCESS";
export const POST_RETRIEVEWHATIF_ERROR = "POST_RETRIEVEWHATIF_ERROR";
export const POST_SUBMITWHATIF_REQUEST = "POST_SUBMITWHATIF_REQUEST";
export const POST_SUBMITWHATIF_SUCCESS = "POST_SUBMITWHATIF_SUCCESS";
export const POST_SUBMITWHATIF_ERROR = "POST_SUBMITWHATIF_ERROR";
export const POST_POTYPEWHATIF_REQUEST = "POST_POTYPEWHATIF_REQUEST";
export const POST_POTYPEWHATIF_SUCCESS = "POST_POTYPEWHATIF_SUCCESS";
export const POST_POTYPEWHATIF_ERROR = "POST_POTYPEWHATIF_ERROR";
export const POST_SUPPLIERWHATIF_REQUEST = "POST_SUPPLIERWHATIF_REQUEST";
export const POST_SUPPLIERWHATIF_SUCCESS = "POST_SUPPLIERWHATIF_SUCCESS";
export const POST_SUPPLIERWHATIF_ERROR = "POST_SUPPLIERWHATIF_ERROR";
export const POST_ORIGINCRTYWHATIF_REQUEST = "POST_ORIGINCRTYWHATIF_REQUEST";
export const POST_ORIGINCRTYWHATIF_SUCCESS = "POST_ORIGINCRTYWHATIF_SUCCESS";
export const POST_ORIGINCRTYWHATIF_ERROR = "POST_ORIGINCRTYWHATIF_ERROR";

export const POST_UPDATEPO_REQUEST = "POST_UPDATEPO_REQUEST";
export const POST_UPDATEPO_SUCCESS = "POST_UPDATEPO_SUCCESS";
export const POST_UPDATEPO_ERROR = "POST_UPDATEPO_ERROR";


//WHATIFPO
export const POST_RETRIEVEWHATIFPO_REQUEST = "POST_RETRIEVEWHATIFPO_REQUEST";
export const POST_RETRIEVEWHATIFPO_SUCCESS = "POST_RETRIEVEWHATIFPO_SUCCESS";
export const POST_RETRIEVEWHATIFPO_ERROR = "POST_RETRIEVEWHATIFPO_ERROR";

export const POST_SUBMITWHATIFPO_REQUEST = "POST_SUBMITWHATIFPO_REQUEST";
export const POST_SUBMITWHATIFPO_SUCCESS = "POST_SUBMITWHATIFPO_SUCCESS";
export const POST_SUBMITWHATIFPO_ERROR = "POST_SUBMITWHATIFPO_ERROR";

// WHAT IF PO PREVIEW
export const POST_RTVPOPRV_REQUEST = "POST_RTVPOPRV_REQUEST";
export const POST_RTVPOPRV_SUCCESS = "POST_RTVPOPRV_SUCCESS";
export const POST_RTVPOPRV_ERROR = "POST_RTVPOPRV_ERROR";

export const POST_CRTPO_REQUEST = "POST_CRTPO_REQUEST";
export const POST_CRTPO_SUCCESS = "POST_CRTPO_SUCCESS";
export const POST_CRTPO_ERROR = "POST_CRTPO_ERROR";

//ERROR REPORT

export const POST_ERRREPORT_REQUEST = "POST_ERRREPORT_REQUEST";
export const POST_ERRREPORT_SUCCESS = "POST_ERRREPORT_SUCCESS";
export const POST_ERRREPORT_ERROR = "POST_ERRREPORT_ERROR";

//APPROVEFUNCTION
export const POST_APPROVEFUNCTION_REQUEST = "POST_APPROVEFUNCTION_REQUEST";
export const POST_APPROVEFUNCTION_SUCCESS = "POST_APPROVEFUNCTION_SUCCESS";
export const POST_APPROVEFUNCTION_ERROR = "POST_APPROVEFUNCTION_ERROR";
export const POST_APPROVEVALIDFUNCTION_REQUEST = "POST_APPROVEVALIDFUNCTION_REQUEST";
export const POST_APPROVEVALIDFUNCTION_SUCCESS = "POST_APPROVEVALIDFUNCTION_SUCCESS";
export const POST_APPROVEVALIDFUNCTION_ERROR = "POST_APPROVEVALIDFUNCTION_ERROR";

/*ALLOCATION SUMMARY  */
export const GET_AllTRSTS_REQUEST = "GET_AllTRSTS_REQUEST";
export const GET_AllTRSTS_SUCCESS = "GET_AllTRSTS_SUCCESS";
export const GET_AllTRSTS_ERROR = "GET_AllTRSTS_ERROR";

export const POST_ALLOCIDS_REQUEST = "POST_ALLOCIDS_REQUEST";
export const POST_ALLOCIDS_SUCCESS = "POST_ALLOCIDS_SUCCESS";
export const POST_ALLOCIDS_ERROR = "POST_ALLOCIDS_ERROR";


export const POST_SWITCHASY_REQUEST = "POST_SWITCHASY_REQUEST";
export const POST_SWITCHASY_SUCCESS = "POST_SWITCHASY_SUCCESS";
export const POST_SWITCHASY_ERROR = "POST_SWITCHASY_ERROR";

export const POST_SEARCHASY_REQUEST = "POST_SEARCHASY_REQUEST";
export const POST_SEARCHASY_SUCCESS = "POST_SEARCHASY_SUCCESS";
export const POST_SEARCHASY_ERROR = "POST_SEARCHASY_ERROR";

export const POST_COPYASY_REQUEST = "POST_COPYASY_REQUEST";
export const POST_COPYASY_SUCCESS = "POST_COPYASY_SUCCESS";
export const POST_COPYASY_ERROR = "POST_COPYASY_ERROR";

export const POST_VALIDASY_REQUEST = "POST_VALIDASY_REQUEST";
export const POST_VALIDASY_SUCCESS = "POST_VALIDASY_SUCCESS";
export const POST_VALIDASY_ERROR = "POST_VALIDASY_ERROR";

export const POST_MAPRV_REQUEST = "POST_MAPRV_REQUEST";
export const POST_MAPRV_SUCCESS = "POST_MAPRV_SUCCESS";
export const POST_MAPRV_ERROR = "POST_MAPRV_ERROR";

//RESERVEFUNCTION
export const POST_RESERVEFUNCTION_REQUEST = "POST_RESERVEFUNCTION_REQUEST";
export const POST_RESERVEFUNCTION_SUCCESS = "POST_RESERVEFUNCTION_SUCCESS";
export const POST_RESERVEFUNCTION_ERROR = "POST_RESERVEFUNCTION_ERROR";
//WORKSHEETFUNCTION
export const POST_WORKSHEETFUNCTION_REQUEST = "POST_WORKSHEETFUNCTION_REQUEST";
export const POST_WORKSHEETFUNCTION_SUCCESS = "POST_WORKSHEETFUNCTION_SUCCESS";
export const POST_WORKSHEETFUNCTION_ERROR = "POST_WORKSHEETFUNCTION_ERROR";

/*SCHEDULE SCREEN */
export const POST_SCHDLSV_REQUEST = "POST_SCHDLSV_REQUEST";
export const POST_SCHDLSV_SUCCESS = "POST_SCHDLSV_SUCCESS";
export const POST_SCHDLSV_ERROR = "POST_SCHDLSV_ERROR";

export const POST_SCHDLRTV_REQUEST = "POST_SCHDLRTV_REQUEST";
export const POST_SCHDLRTV_SUCCESS = "POST_SCHDLRTV_SUCCESS";
export const POST_SCHDLRTV_ERROR = "POST_SCHDLRTV_ERROR";

/* COMMIT DATA */
export const POST_COMMITDATA_REQUEST = "POST_COMMITDATA_REQUEST";
export const POST_COMMITDATA_SUCCESS = "POST_COMMITDATA_SUCCESS";
export const POST_COMMITDATA_ERROR = "POST_COMMITDATA_ERROR";

/* ALLOC DETAILS PACK*/
export const POST_RTVADPACK_REQUEST = "POST_RTVADPACK_REQUEST";
export const POST_RTVADPACK_SUCCESS = "POST_RTVADPACK_SUCCESS";
export const POST_RTVADPACK_ERROR = "POST_RTVADPACK_ERROR";

export const POST_ADVALIDN_REQUEST = "POST_ADVALIDN_REQUEST";
export const POST_ADVALIDN_SUCCESS = "POST_ADVALIDN_SUCCESS";
export const POST_ADVALIDN_ERROR = "POST_ADVALIDN_ERROR";

export const POST_G1ADPK_REQUEST = "POST_G1ADPK_REQUEST";
export const POST_G1ADPK_SUCCESS = "POST_G1ADPK_SUCCESS";
export const POST_G1ADPK_ERROR = "POST_G1ADPK_ERROR";

export const POST_G2ADPK_REQUEST = "POST_G2ADPK_REQUEST";
export const POST_G2ADPK_SUCCESS = "POST_G2ADPK_SUCCESS";
export const POST_G2ADPK_ERROR = "POST_G2ADPK_ERROR";

export const POST_UPDATEADPK_REQUEST = "POST_UPDATEADPK_REQUEST";
export const POST_UPDATEADPK_SUCCESS = "POST_UPDATEADPK_SUCCESS";
export const POST_UPDATEADPK_ERROR = "POST_UPDATEADPK_ERROR";

export const POST_RESTOREADPK_REQUEST = "POST_RESTOREADPK_REQUEST";
export const POST_RESTOREADPK_SUCCESS = "POST_RESTOREADPK_SUCCESS";
export const POST_RESTOREADPK_ERROR = "POST_RESTOREADPK_ERROR";

/* Multi PO Create Screen*/
export const POST_MULTIPOCREATE_REQUEST = "POST_MULTIPOCREATE_REQUEST";
export const POST_MULTIPOCREATE_SUCCESS = "POST_MULTIPOCREATE_SUCCESS";
export const POST_MULTIPOCREATE_ERROR = "POST_MULTIPOCREATE_ERROR";

/* RL Validation in Create Screen*/
export const POST_VALIDRLCHECKDATA_REQUEST = "POST_VALIDRLCHECKDATA_REQUEST";
export const POST_VALIDRLCHECKDATA_SUCCESS = "POST_VALIDRLCHECKDATA_SUCCESS";
export const POST_VALIDRLCHECKDATA_ERROR = "POST_VALIDRLCHECKDATA_ERROR";


 /*COMMIT/CLOSE ALLOC DETAILS & SIZE DETAILS */
  
 export const POST_ADSAVE_REQUEST = "POST_ADSAVE_REQUEST";
 export const POST_ADSAVE_SUCCESS = "POST_ADSAVE_SUCCESS";
 export const POST_ADSAVE_ERROR = "POST_ADSAVE_ERROR";
 
 export const POST_SDSAVE_REQUEST = "POST_SDSAVE_REQUEST";
 export const POST_SDSAVE_SUCCESS = "POST_SDSAVE_SUCCESS";
 export const POST_SDSAVE_ERROR   = "POST_SDSAVE_ERROR";

 /* DASHBOARD ALLOCATION */

export const POST_DASHBOARDUSERALLOC_REQUEST = "POST_DASHBOARDUSERALLOC_REQUEST";
export const POST_DASHBOARDUSERALLOC_SUCCESS = "POST_DASHBOARDUSERALLOC_SUCCESS";
export const POST_DASHBOARDUSERALLOC_ERROR = "POST_DASHBOARDUSERALLOC_ERROR";

export const POST_DASHBOARDRELEASECOUNT_REQUEST = "POST_DASHBOARDRELEASECOUNT_REQUEST";
export const POST_DASHBOARDRELEASECOUNT_SUCCESS = "POST_DASHBOARDRELEASECOUNT_SUCCESS";
export const POST_DASHBOARDRELEASECOUNT_ERROR = "POST_DASHBOARDRELEASECOUNT_ERROR";

export const POST_DASHBOARDALLOCCOUNT_REQUEST = "POST_DASHBOARDALLOCCOUNT_REQUEST";
export const POST_DASHBOARDALLOCCOUNT_SUCCESS = "POST_DASHBOARDALLOCCOUNT_SUCCESS";
export const POST_DASHBOARDALLOCCOUNT_ERROR = "POST_DASHBOARDALLOCCOUNT_ERROR";

export const GET_DALLOC_REQUEST = "GET_DALLOC_REQUEST";
export const GET_DALLOC_SUCCESS = "GET_DALLOC_SUCCESS";
export const GET_DALLOC_ERROR =   "GET_DALLOC_ERROR";


/* Collab Comments */
export const POST_RTVCOMM_REQUEST = "POST_RTVCOMM_REQUEST";
export const POST_RTVCOMM_SUCCESS = "POST_RTVCOMM_SUCCESS";
export const POST_RTVCOMM_ERROR =   "POST_RTVCOMM_ERROR";

export const POST_INSCOMM_REQUEST = "POST_INSCOMM_REQUEST";
export const POST_INSCOMM_SUCCESS = "POST_INSCOMM_SUCCESS";
export const POST_INSCOMM_ERROR =   "POST_INSCOMM_ERROR";

/* ALLOCATION BATCHES */
export const POST_ALCSCHLBTH_REQUEST = "POST_ALCSCHLBTH_REQUEST";
export const POST_ALCSCHLBTH_SUCCESS = "POST_ALCSCHLBTH_SUCCESS";
export const POST_ALCSCHLBTH_ERROR =   "POST_ALCSCHLBTH_ERROR";

export const POST_UPDBTHDATE_REQUEST = "POST_UPDBTHDATE_REQUEST";
export const POST_UPDBTHDATE_SUCCESS = "POST_UPDBTHDATE_SUCCESS";
export const POST_UPDBTHDATE_ERROR =   "POST_UPDBTHDATE_ERROR";

/* RL TEMPLATE STARTS */
export const POST_RULESAVETEMPLATE_REQUEST = "POST_RULESAVETEMPLATE_REQUEST";
export const POST_RULESAVETEMPLATE_SUCCESS = "POST_RULESAVETEMPLATE_SUCCESS";
export const POST_RULESAVETEMPLATE_ERROR = "POST_RULESAVETEMPLATE_ERROR";

export const POST_RLLOCSAVETEMPLATE_REQUEST = "POST_RLLOCSAVETEMPLATE_REQUEST";
export const POST_RLLOCSAVETEMPLATE_SUCCESS = "POST_RLLOCSAVETEMPLATE_SUCCESS";
export const POST_RLLOCSAVETEMPLATE_ERROR = "POST_RLLOCSAVETEMPLATE_ERROR";

export const GET_RULETEMPLATENAME_REQUEST = "GET_RULETEMPLATENAME_REQUEST";
export const GET_RULETEMPLATENAME_SUCCESS = "GET_RULETEMPLATENAME_SUCCESS";
export const GET_RULETEMPLATENAME_ERROR = "GET_RULETEMPLATENAME_ERROR";

export const GET_RLLOCTEMPLATENAME_REQUEST = "GET_RLLOCTEMPLATENAME_REQUEST";
export const GET_RLLOCTEMPLATENAME_SUCCESS = "GET_RLLOCTEMPLATENAME_SUCCESS";
export const GET_RLLOCTEMPLATENAME_ERROR = "GET_RLLOCTEMPLATENAME_ERROR";

export const POST_FETCHRULETEMPLATE_REQUEST = "POST_FETCHRULETEMPLATE_REQUEST";
export const POST_FETCHRULETEMPLATE_SUCCESS = "POST_FETCHRULETEMPLATE_SUCCESS";
export const POST_FETCHRULETEMPLATE_ERROR = "POST_FETCHRULETEMPLATE_ERROR";

export const POST_FETCHRLLOCTEMPLATE_REQUEST = "POST_FETCHRLLOCTEMPLATE_REQUEST";
export const POST_FETCHRLLOCTEMPLATE_SUCCESS = "POST_FETCHRLLOCTEMPLATE_SUCCESS";
export const POST_FETCHRLLOCTEMPLATE_ERROR = "POST_FETCHRLLOCTEMPLATE_ERROR";
/* RL TEMPLATE ENDS */

/* SEED DATA INSERT  START*/
export const POST_SEEDHIER1_REQUEST = "POST_SEEDHIER1_REQUEST";
export const POST_SEEDHIER1_SUCCESS = "POST_SEEDHIER1_SUCCESS";
export const POST_SEEDHIER1_ERROR =   "POST_SEEDHIER1_ERROR";

export const POST_SEEDHIER2_REQUEST = "POST_SEEDHIER2_REQUEST";
export const POST_SEEDHIER2_SUCCESS = "POST_SEEDHIER2_SUCCESS";
export const POST_SEEDHIER2_ERROR =   "POST_SEEDHIER2_ERROR";


export const POST_SEEDHIER3_REQUEST = "POST_SEEDHIER3_REQUEST";
export const POST_SEEDHIER3_SUCCESS = "POST_SEEDHIER3_SUCCESS";
export const POST_SEEDHIER3_ERROR =   "POST_SEEDHIER3_ERROR";

export const POST_SEEDITMDTL_REQUEST = "POST_SEEDITMDTL_REQUEST";
export const POST_SEEDITMDTL_SUCCESS = "POST_SEEDITMDTL_SUCCESS";
export const POST_SEEDITMDTL_ERROR =   "POST_SEEDITMDTL_ERROR";
/* SEED DATA INSERT END*/

/* REPORT START */
export const GET_REPORT_REQUEST = "GET_REPORT_REQUEST";
export const GET_REPORT_SUCCESS = "GET_REPORT_SUCCESS";
export const GET_REPORT_ERROR = "GET_REPORT_ERROR";

/* REPORT END */
/* USER VALIDATIONS  START*/
export const POST_USRDTLS_REQUEST = "POST_USRDTLS_REQUEST";
export const POST_USRDTLS_SUCCESS = "POST_USRDTLS_SUCCESS";
export const POST_USRDTLS_ERROR =   "POST_USRDTLS_ERROR";

export const POST_USRSDATA_REQUEST = "POST_USRSDATA_REQUEST";
export const POST_USRSDATA_SUCCESS = "POST_USRSDATA_SUCCESS";
export const POST_USRSDATA_ERROR =   "POST_USRSDATA_ERROR";

/* USER VALIDATIONS END*/

/* SUBMITTED ALLOC STATUS */
export const POST_UPDSTATUS_REQUEST = "POST_UPDSTATUS_REQUEST";
export const POST_UPDSTATUS_SUCCESS = "POST_UPDSTATUS_SUCCESS";
export const POST_UPDSTATUS_ERROR =   "POST_UPDSTATUS_ERROR";