export const headCells = [
  {
    id: "PRIMARY_ACCOUNT",
    numeric: true,
    disablePadding: true,
    label: "PRIMARY_ACCOUNT",
    width: "100%",
  },
  {
    id: "SET_OF_BOOKS_ID",
    numeric: false,
    disablePadding: true,
    label: "SET_OF_BOOKS_ID",
    width: "100%",
  },
  {
    id: "SEGMENT1",
    numeric: true,
    disablePadding: true,
    label: "SEGMENT1",
    width: "100%",
  },
  {
    id: "SEGMENT2",
    numeric: false,
    disablePadding: true,
    label: "SEGMENT2",
    width: "100%",
  },
  {
    id: "SEGMENT3",
    numeric: false,
    disablePadding: true,
    label: "SEGMENT3",
    width: "100%",
  },
  {
    id: "SEGMENT4",
    numeric: false,
    disablePadding: true,
    label: "SEGMENT4",
    width: "100%",
  },
  {
    id: "SEGMENT5",
    numeric: false,
    disablePadding: true,
    label: "SEGMENT5",
    width: "100%",
  },
  {
    id: "SEGMENT6",
    numeric: true,
    disablePadding: true,
    label: "SEGMENT6",
    width: "100%",
  },
  {
    id: "SEGMENT7",
    numeric: true,
    disablePadding: true,
    label: "SEGMENT7",
    width: "100%",
  },
  {
    id: "CURRENCY",
    numeric: true,
    disablePadding: true,
    label: "CURRENCY",
    width: "100%",
  },
  {
    id: "CREATE_ID",
    numeric: true,
    disablePadding: true,
    label: "USER",
    width: "100%",
  },
  {
    id: "CREATE_DATETIME",
    numeric: true,
    disablePadding: true,
    label: "CREATE_DATETIME",
    width: "100%",
  },

];
